// Angular/day14-15 - store/src/app/product-details/product-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductModel } from '../models/product.model';
import { ActivatedRoute, Router } from '@angular/router';
import { ProductService } from '../services/product.service';
import { HttpClient } from '@angular/common/http';


@Component({
  selector: 'app-product-details',
  templateUrl: './product-details.component.html',
  styleUrls: ['./product-details.component.css']
})
export class ProductDetailsComponent implements OnInit {
  product!: ProductModel ;

  constructor(
    private _activatedRoute: ActivatedRoute,
    private _productService: ProductService,
    private _http: HttpClient
  ) { }

  productId!: string;


  ngOnInit(): void {
    this.productId = this._activatedRoute.snapshot.queryParams['id'];
  
    this._http
      .get<ProductModel>(`https://fakestoreapi.com/products/${this.productId}`)
      .subscribe({
        next: (res: ProductModel) => {
          console.log(res);
          this.product = res;
        },  
      });
  }
    
  onAddToCart() {
    this._productService.onCountIncrement();
  }
}
<div class="row">
    <div class="col-md-6">
        <img class="img-fluid" [src]="product.image" alt="Card image cap" />
    </div>
    <div class=" col-md-6 d-flex align-items-center">
        <div class="fw-bold">
            <h1>{{ product.title }}</h1>
            <p>Description: {{ product.description }}</p>
            <p class="fw-bold">Price: {{ product.price | egyCurrent }}</p>
            <div class="d-flex justify-content-between">
                <a class="btn btn-success" > Add to cart </a>
                <a href="#" class="btn btn-primary">Back to Products</a>
            </div>
        </div>
    </div>
</div>

// React.js/day18-19-ecommerce/src/components/products/ProductDetails.jsx
import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { getProductById } from '../../services/product.service';

export const ProductDetails = () => {
  const { id } = useParams();
  const [product, setProduct] = useState(null);

  const getProduct = async (id) => {
    const product = await getProductById(id);
    setProduct(product);
  };

  useEffect(() => {
    getProduct(id);
  }, [id]);

  return (
    <div className="row">
      {product && (
        <>
          <div className="col-md-6">
            <img src={product.thumbnail} alt="Card image cap" className="img-fluid" />
          </div>
          <div className="col-md-6 d-flex align-items-center">
            <div className="fw-bold">
              <h1>{product.title}</h1>
              <p>Description: {product.description}</p>
              <p className="fw-bold">Price: {product.price} $</p>
              <div className="d-flex justify-content-between">
                <button className="btn btn-success">Add to cart</button>
                <Link to="/Products" className="btn btn-primary">
                  Back to Products
                </Link>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
