// Angular/day14-15 - store/src/app/shared/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { ProductService } from 'src/app/services/product.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {

count!:number;

constructor(private _productService:ProductService){
  
  this._productService.currentCount$.subscribe({
    next: (count: number) => {
      this.count = count;
    },
    error: (error) => {
      console.log(error);
    },
  });
}


}

<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" routerLink="/">STORE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white" aria-current="page" routerLink="/">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" routerLink="/cart">
            <span class="p-1 bg-white rounded-circle">{{
              count
              }}</span>
            <span class="text-white" routerLink="/cart">Cart</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" aria-current="page" routerLink="/auth">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" routerLink="/auth/register">Register</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

// React.js/day16-portflio/src/components/Navbar/Navbar.jsx
import React from 'react'
import styles from './navbar.module.css'
const Navbar = () => {
  return (
    <div className={styles.Navbar}>
      {/* <div 
  className="collapse mt-5"
  id="navbarToggleExternalContent"
  data-bs-theme="dark"
>
  
  <div className="bg-dark p-4 ">
    <h5 className="text-body-emphasis h4">Collapsed content</h5>
    <span className="text-body-secondary">Toggleable via the navbar brand.</span>
  </div>
</div> */}

<nav className="navbar navbar-dark bg-dark fixed-top">
  <div className="container-fluid">
    <h2 className="text-white">Yungy</h2>
    <button
      className="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarToggleExternalContent"
      aria-controls="navbarToggleExternalContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

    </div>
  )
}

export default Navbar
